files:
  include: 'app/stylesheets/**/*.scss'

rules:
  force-pseudo-nesting: 0
  single-line-per-selector: 0
  class-name-format:
    - 2
    -
      convention: 'hyphenatedbem'
  pseudo-element: 0
  indentation:
    - 2
    -
      size: 2
